name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    if: github.repository == 'n0isy/brain-pause' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin ${{ vars.REGISTRY }}

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --cache-from ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest \
            -t ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
